# Generated by Django 4.2.4 on 2023-09-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_resource_related_user_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdResources', to='testapp.user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ownedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedResources', to='testapp.user'),
        ),
    ]
